// examples/vue-pwa/src/Counter.vue
<script setup lang="ts">
import { ref } from 'vue';

defineOptions({ name: 'Counter' });

const props = defineProps<{ initial: number; step: number }>();
const count = ref(props.initial);
</script>

<template>
  <section>
    <p>counter-marker: {{ count }}</p>
    <button type="button" @click="count -= props.step">-</button>
    <button type="button" @click="count += props.step">+</button>
  </section>
</template>

// examples/react-pwa/src/Counter.tsx
import { useState } from 'react';

export type CounterProps = {
  readonly initial: number;
  readonly step: number;
};

export const Counter = ({ initial, step }: CounterProps): JSX.Element => {
  const [count, setCount] = useState(initial);
  return (
    <section>
      <p>counter-marker: {count}</p>
      <button type="button" onClick={() => setCount((c) => c - step)}>
        -
      </button>
      <button type="button" onClick={() => setCount((c) => c + step)}>
        +
      </button>
    </section>
  );
};

Counter.displayName = 'Counter';
