// examples/react-pwa/src/UserProfile.tsx
export type UserProfileProps = {
  readonly name: string;
  readonly role: string;
};

export const UserProfile = ({ name, role }: UserProfileProps): JSX.Element => (
  <section role="region" aria-label="user profile">
    <h2>user-profile-marker</h2>
    <p>name: {name}</p>
    <p>role: {role}</p>
  </section>
);

UserProfile.displayName = 'UserProfile';

// examples/vue-pwa/src/UserProfile.vue
<script setup lang="ts">
defineOptions({ name: 'UserProfile' });

defineProps<{ name: string; role: string }>();
</script>

<template>
  <section role="region" aria-label="user profile">
    <h2>user-profile-marker</h2>
    <p>name: {{ name }}</p>
    <p>role: {{ role }}</p>
  </section>
</template>
